### ISSUE TITLE
DefaultCompletionSubscriber doesn't redeem CompletionStage

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-streams-operators#129]
Interface javadoc says
```java
/**
 * A subscriber that redeems a completion stage when it completes.
 * <p>
 * The result is provided through a {@link CompletionStage}, which is redeemed when the subscriber receives a
 * completion or error signal, or otherwise cancels the stream.
 * <p>
```
But [DefaultCompletionSubscriber](https://github.com/eclipse/microprofile-reactive-streams-operators/blob/master/api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/CompletionSubscriber.java) does nothing with supplied CompletionStage in both cases:
```java
            @Override
            public void onError(Throwable throwable) {
                subscriber.onError(throwable);
            }

            @Override
            public void onComplete() {
                subscriber.onComplete();
            }
```

**Comment by akarnokd** [comment]
What's even more odd is that no test fails because of this.

**Comment by Azquelt** [comment]
`DefaultCompletionSubscriber` really just holds both a `Subscriber` and a `CompletionStage` and delegates calls to the `Subscriber`.

It's up to the creator of the `DefaultCompletionSubscriber` to ensure that the `CompletionStage` passed into `CompletionSubscriber.of` is redeemed when the subscriber completes or terminates.

In the core implmentation, the `CompletionStage` is obtained from [the call to `engine.buildSubscriber`](https://github.com/eclipse/microprofile-reactive-streams-operators/blob/48a38ed12ae9756c062be5a5007aeab87f166671/core/src/main/java/org/eclipse/microprofile/reactive/streams/operators/core/SubscriberBuilderImpl.java#L44-L45).

As a side note, there's actually no way to manually redeem a `CompletionStage` via that interface. It's up to the `CompletionStage` implementation as to how it gets redeemed. Usually, the implementation is `CompletableFuture` and it's redeemed using the `complete` method.

**Comment by danielkec** [comment]
It does not seems right for it to be part of the API as it may lead to wrong conclusions. Maybe change the javadoc of the `of` method for something like: `Create wrapper for already associated CompletionStage and Subscriber`, to make it clear what is expected?

**Comment by Azquelt** [comment]
Yes, I think that makes sense.

**Comment by Azquelt** [comment]
I've opened #150 to make it clear what the caller's responsibilities are if you'd like to take a look @danielkec.
