### ISSUE TITLE
Null expectation of flatMapCompletionStage & Stage.FlatMapCompletionStage

### ISSUE THREAD

**Issue by akarnokd** [eclipse/microprofile-reactive-streams-operators#135]
The documentation of `...Builder.flatMapCompletionStage` and `Stage.FlatMapCompletionStage` don't describe what to do when the mapped-in `CompletionStage` signals `null`, unlike `ReactiveStreamsFactory.fromCompletionStageNullable`.

Since there is no `flatMapCompletionStageNullable` in the API, it is unclear to me if the equivalent throwing behavior should be provided or not.

What is the expected behavior?

**Comment by Emily-Jiang** [comment]
@cescoffier can you clarify what is the expected behaviour?

**Comment by cescoffier** [comment]
The current behavior would produce a failure. It's very inconvenient I would say.

**Comment by Emily-Jiang** [comment]
Document that this method will throw NPE when null is passed in.
