### ISSUE TITLE
How to turn Builder.flatMap into a Stage.FlatMap?

### ISSUE THREAD

**Issue by akarnokd** [eclipse/microprofile-reactive-streams-operators#138]
The signature of `...Builder.flatMap(Function<? super T, ? extends PublisherBuilder<? extends S>> mapper)` accepts `PublisherBuilder`. However, if I want to represent this method as a `Stage.FlatMap` to be used with `buildRs(ReactiveStreamsEngine)` via `engine.buildPublisher(Graph)`, `Stage.FlatMap` requires a `Function<T, Graph>`. 

How do I supposedly turn an arbitrary `PublisherBuilder` into a `Graph`? Should I create a mock engine so that when calling `PublisherBuilder.buildRs(ReactiveStreamsEngine)`, it captures the `Graph` object sent to its `buildPublisher(Graph)`?

**Comment by Emily-Jiang** [comment]
It was documented in the graph section in the spec for the cast.

**Comment by Azquelt** [comment]
As you noted in #140, a compliant implementation of `PublisherBuilder` must also implement `ToGraphable` so you can just cast to `ToGraphable` and call `toGraph()`.
