### ISSUE TITLE
ToGraphable not implemented by the interfaces its docs say they should

### ISSUE THREAD

**Issue by akarnokd** [eclipse/microprofile-reactive-streams-operators#140]
The Javadoc of `ToGraphable` mandates `PublisherBuilder`, `ProcessorBuilder`, `SubscriberBuilder` and
`CompletionRunner` instances implement it, yet the interfaces do not extend `ToGraphable` to ensure this.

Without it, the TCK fails with ClassCastExceptions.

Is this an oversight or deliberate?

**Comment by Emily-Jiang** [comment]
From @cescoffier , It is deliberate as we want to hide the interface from the users.
