### ISSUE TITLE
MicroProfile Reactive Streams Operator implementation to version 2.0

### ISSUE THREAD

**Issue by otaviojava** [eclipse/microprofile-reactive-streams-operators#166]
I checked that there is [version 2.0 of the API](https://mvnrepository.com/artifact/org.eclipse.microprofile.reactive-streams-operators/microprofile-reactive-streams-operators-api/2.0).
However, there is no implementation.
When I checked the vendors, [in the read.me file](https://github.com/eclipse/microprofile-reactive-streams-operators#implementations), I could see that those stopped, and there is [one archived](https://github.com/smallrye/smallrye-reactive-streams-operators).

Is there any new vendor/implementation to support this new API? If not, does it make sense to keep an API without vendors?

**Comment by cescoffier** [comment]
Mutiny implements the version 2.0 of the API: https://github.com/smallrye/smallrye-mutiny/tree/main/reactive-streams-operators

**Comment by otaviojava** [comment]
Thank you @cealsair 
I've created PR to include this option in the README file:
https://github.com/eclipse/microprofile-reactive-streams-operators/pull/167
