### ISSUE TITLE
More examples specific to Reactive Streams

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams-operators#32]
From @venkats:

> The examples given at https://github.com/eclipse/microprofile-reactive/blob/master/streams/spec/src/main/asciidoc/examples.asciidoc are very similar to what Java 8 streams can do. It may be better to show examples that are different. For instance, how are errors handled, how do we perform tasks in a different thread? In other words, seeing enough difference from the use of Stream may benefit the reader as to how this implementation is (a) different from Stream, while parts of it is similar and (b) how they can truly work with asynchrony instead of parallel.

**Comment by jroper** [comment]
One reason why the document currently only has use cases similar to Java 8 streams is because in this first iteration of the API, we've focused on only providing the same scope of API. But, as we add additional reactive streams specific features, such as error handling and backpressure management, we need to make sure we update the examples and make these use cases prominent, so as to showcase the value of the spec.

**Comment by jroper** [comment]
Also related from @venkats:

> It will be very useful to have examples that show how backpressure is handled. This again is a significant departure from the Stream API and will be very useful to someone exploring this.

**Comment by Emily-Jiang** [comment]
@cescoffier @Azquelt suggested not to add more things as it potentially brings more confusion. Close this for now.
