### ISSUE TITLE
What additional methods should we have?

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams-operators#34]
From @venkats:

> I am quite eager to see implementations of highly useful methods like zip, scan, etc. These are very lacking in the (Java 8) Stream API and I think it is critical to have these methods.

Related to #9. As discussed in #9, for the first version of this API we want to primarily focus on functionality that's useful to messaging, and specifically the messaging spec, other operators can be added in future versions of the API - for those future versions of the API we can define new applications of the API and therefore come up with new operators that will be useful in those applications.

But for now, there most likely are operators that will be useful users of the messaging spec, so the question is, what are they, and what use cases will they fulfil?

**Comment by hutchig** [comment]
This discussion also makes clear another discussion we were having...it is really clear that these operators should be called exactly that "operators" and nothing else. 
http://projectreactor.io/docs/core/release/reference/#which-operator
http://reactivex.io/documentation/operators.html

**Comment by cescoffier** [comment]
I've also opened #51 to discuss the method from the Java Stream APIs.

**Comment by hutchig** [comment]
https://doc.akka.io/docs/akka/2.5/stream/operators/Source-or-Flow/mapAsyncUnordered.html
gets a big thumbs up in a presentation on Paypal's squbs suite. 
https://www.lightbend.com/blog/lessons-learned-from-paypal-implementing-back-pressure-with-akka-streams-and-kafka

**Comment by Emily-Jiang** [comment]
This is resolved via #51
